language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

install:
  - curl -s http://getcomposer.org/installer | php
  - composer require satooshi/php-coveralls:~1.0@stable
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
