language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_script:
  - travis_retry composer self-update

install:
   - composer require --dev orchestra/testbench:${ORCHESTRA_VERSION}

script: phpunit
