language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - LARAVEL_VERSION="4.0.*" ORCHESTRA_VERSION="2.0.*"
  - LARAVEL_VERSION="4.1.*" ORCHESTRA_VERSION="2.1.*"
  - LARAVEL_VERSION="4.2.*" ORCHESTRA_VERSION="2.2.*"

install:
  - curl -s http://getcomposer.org/installer | php
  - composer require satooshi/php-coveralls:~1.0@stable --no-update
  - composer require --dev orchestra/testbench:${ORCHESTRA_VERSION} --no-update
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls